export const CARD_IDS = {
  zhuoZhuoTianYan: 'ly-zhuozhuotianyan',
  xingHongJuYi: 'dq-xinghongjuyi',
  erWeiYaoHu: 'dq-erweiyaohu',
  liuWeiMoHu: 'dq-liuweimohu',
  mengHu: 'dq-menghu',
  suiShou: 'dq-suishou',
  chiYanTianHuan: 'ly-chiyantianhuan',
  lieHuoLiaoYuan: 'ly-liehuoliaoyuan',
  lieYanFenShen: 'ly-lieyanfenshen',
  shenHuoBengFa: 'ly-shenhuobengfa',
  tianHuoYunXing: 'ly-tianhuoyunxing',
  ningBingShuangHua: 'ly-ningbingshuanghua',
  shangGuanCe: 'dq-shangguance',
  zuoGui: 'dq-zuogui',
  wenMin: 'dq-wenmin',
  qiHao: 'dq-qihao',
  yanHong: 'dq-yanhong',
  hanJingCi: 'ly-hanjingci',
  shuangHanPoLie: 'ly-shuanghanpolie',
  linShuangHanYong: 'ly-linshuanghanyong',
  shuangCiHanYu: 'ly-shuangcihanyu',
  hanChaoBingYong: 'ly-hanchaobingyong',
  leiYouLingGuang: 'ly-leiyoulingguang',
  yinLeiFan: 'dq-yinleifan',
  leiPoJing: 'dq-leipojing',
  lianLeiBi: 'dq-lianleibi',
  ziLeiHu: 'dq-zileihu',
  ziDianChiWen: 'dq-zidianchiwen',
  leiTingZhenJi: 'ly-leitingzhenji',
  jingLeiJi: 'ly-jingleiji',
  tianLeiHuYou: 'ly-tianleihuyou',
  wuLeiZhu: 'ly-wuleizhu',
  jiuXiaoLeiDong: 'ly-jiuxiaoleidong',
  qingWuFuSheng: 'ly-qingwufusheng',
  zheShan: 'dq-zheshan',
  shenMuTou_dq: 'dq-shenmutou',
  linFeng: 'dq-linfeng',
  qingLiangZhu: 'dq-qingliangzhu',
  liuHeJing: 'dq-liuhejing',
  shenMuTou_ly: 'ly-shenmutou',
  muYinQingLing: 'ly-muyinqingling',
  fuMuZhangFeng: 'ly-fumuzhangfeng',
  cangLinFuSheng: 'ly-canglinfusheng',
  lieDiBeng: 'ly-liedibeng',
} as const

export type CardId = (typeof CARD_IDS)[keyof typeof CARD_IDS]
